<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NoWarn>$(NoWarn);CS0649</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\AutomationModels.cs" Link="AutomationModels.cs" />
    <Compile Include="Program.cs" />
  </ItemGroup>
</Project>
