#!/usr/bin/env python3
"""Extract bounded WRAM ranges from a DKCFirstDivergenceLocator report."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys
from typing import Any
import uuid

KINDS = ("selectedMemory", "allMemory", "ignoredMemory", "unselectedMemory")
WRAM_BASE = 0x7E0000
WRAM_END = 0x7FFFFF


class RangePreparationError(ValueError):
    pass


def parse_address(value: Any) -> int:
    if not isinstance(value, str) or not re.fullmatch(r"(?:0x|\$)?[0-9A-Fa-f]+", value.strip()):
        raise RangePreparationError(f"invalid report WRAM address: {value!r}")
    token = value.strip()
    if token.startswith("$"):
        token = token[1:]
    elif token.lower().startswith("0x"):
        token = token[2:]
    address = int(token, 16)
    if not WRAM_BASE <= address <= WRAM_END:
        raise RangePreparationError(f"report address is outside $7E0000-$7FFFFF: {value}")
    return address


def case_key(case: dict[str, Any]) -> str:
    return f"{case.get('state', '')}/{case.get('scenario', '')}"


def choose_case(report: dict[str, Any], requested: str | None) -> dict[str, Any]:
    if report.get("tool") != "DKCFirstDivergenceLocator" or report.get("schemaVersion") != 1:
        raise RangePreparationError("input is not a schemaVersion 1 DKCFirstDivergenceLocator report")
    cases = report.get("cases")
    if not isinstance(cases, list) or not cases:
        raise RangePreparationError("report has no cases")
    if requested:
        matches = [case for case in cases if isinstance(case, dict) and case_key(case) == requested]
        if len(matches) != 1:
            available = ", ".join(case_key(case) for case in cases if isinstance(case, dict))
            raise RangePreparationError(f"case {requested!r} was not unique; available: {available}")
        return matches[0]
    located = [case for case in cases if isinstance(case, dict) and isinstance(case.get("difference"), dict)]
    if len(located) != 1:
        available = ", ".join(case_key(case) for case in located)
        raise RangePreparationError(f"select --case because {len(located)} located cases are present: {available}")
    return located[0]


def extract_ranges(report: dict[str, Any], requested_case: str | None, kind: str,
                   max_ranges: int, max_bytes: int) -> tuple[str, list[tuple[int, int]]]:
    if kind not in KINDS:
        raise RangePreparationError(f"unsupported difference kind: {kind}")
    case = choose_case(report, requested_case)
    difference = case.get("difference")
    if not isinstance(difference, dict):
        raise RangePreparationError(f"case {case_key(case)} has no located difference")
    section = difference.get(kind)
    if not isinstance(section, dict):
        raise RangePreparationError(f"case {case_key(case)} has no difference.{kind} section")
    if section.get("rangesTruncated"):
        raise RangePreparationError(f"difference.{kind}.ranges is truncated; refusing an incomplete watch plan")
    raw_ranges = section.get("ranges")
    if not isinstance(raw_ranges, list) or not raw_ranges:
        raise RangePreparationError(f"difference.{kind} has no changed ranges")
    parsed: list[tuple[int, int]] = []
    for index, item in enumerate(raw_ranges, 1):
        if not isinstance(item, dict):
            raise RangePreparationError(f"range {index} is not an object")
        start = parse_address(item.get("start"))
        end = parse_address(item.get("end"))
        if end < start:
            raise RangePreparationError(f"range {index} ends before it starts")
        declared = item.get("length")
        if declared is not None and declared != end - start + 1:
            raise RangePreparationError(f"range {index} length disagrees with its endpoints")
        parsed.append((start, end))
    parsed.sort()
    for previous, current in zip(parsed, parsed[1:]):
        if current[0] <= previous[1]:
            raise RangePreparationError("report contains overlapping ranges")
    total = sum(end - start + 1 for start, end in parsed)
    if len(parsed) > max_ranges:
        raise RangePreparationError(f"plan has {len(parsed)} ranges; limit is {max_ranges}")
    if total > max_bytes:
        raise RangePreparationError(f"plan covers {total} bytes; limit is {max_bytes}")
    return case_key(case), parsed


def render_ranges(selected_case: str, kind: str, ranges: list[tuple[int, int]]) -> str:
    lines = [
        "# Generated by prepare_ranges.py from DKCFirstDivergenceLocator schema 1.",
        f"# case={selected_case} difference={kind}",
    ]
    for index, (start, end) in enumerate(ranges, 1):
        lines.append(f"${start:06X}-${end:06X} first-divergence-{kind}-{index:03d}")
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("report", type=Path, help="FirstDivergence report.json")
    parser.add_argument("--case", help="Exact STATE/SCENARIO key; required when multiple located cases exist")
    parser.add_argument("--kind", choices=KINDS, default="selectedMemory")
    parser.add_argument("--output", type=Path, help="Destination ranges.txt; omitted with --validate-only")
    parser.add_argument("--max-ranges", type=int, default=64)
    parser.add_argument("--max-bytes", type=int, default=4096)
    parser.add_argument("--validate-only", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.max_ranges <= 0 or args.max_bytes <= 0:
        raise RangePreparationError("limits must be positive")
    report = json.loads(args.report.read_text(encoding="utf-8"))
    selected_case, ranges = extract_ranges(report, args.case, args.kind, args.max_ranges, args.max_bytes)
    contents = render_ranges(selected_case, args.kind, ranges)
    if args.validate_only:
        print(f"PASS: {selected_case} {args.kind}: {len(ranges)} ranges, {sum(end-start+1 for start,end in ranges)} bytes")
        return 0
    if args.output is None:
        raise RangePreparationError("--output is required unless --validate-only is used")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    temporary = args.output.with_name(args.output.name + f".tmp-{uuid.uuid4().hex}")
    try:
        temporary.write_text(contents, encoding="utf-8", newline="\n")
        temporary.replace(args.output)
    finally:
        temporary.unlink(missing_ok=True)
    print(f"Wrote {args.output}: {len(ranges)} ranges for {selected_case} ({args.kind})")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, json.JSONDecodeError, RangePreparationError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        raise SystemExit(2)
