<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>10.0</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>DKC-Widescreen-Patcher</AssemblyName>
    <RootNamespace>DkcWidescreenPatcher</RootNamespace>
    <Version>1.1.0</Version>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup Condition="'$(PatchResourceDirectory)' != ''">
    <EmbeddedResource Include="$(PatchResourceDirectory)\*.bps">
      <LogicalName>DkcWidescreenPatcher.Patches.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
